[package]
name = "wal"
version = "0.1.2"
authors = ["Dan Burkert <dan@danburkert.com>", "Andrey Vasnetsov <andrey@vasnetsov.com>"]

[dependencies]
byteorder = "0.4"
crc = "1"
eventual = "0.1.4"
fs2 = "0.4"
log = "0.4"
memmap = "0.5.2"
rand = "0.4.6"
time = "0.3"

# Binary dependencies
docopt = "1.1"
env_logger = "0.9"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
docopt = "1.1"
env_logger = "0.9"
histogram = "0.6"
quickcheck = "0.2"
regex = "1.5"
rustc-serialize = "0.3"
tempdir = "0.3"
